/*
 * KFilter6
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2002-2026 Martin Erdtmann
 */

#include "correctioncurveexport.h"

#include <QLocale>
#include <QSaveFile>
#include <QStringConverter>
#include <QTextStream>

#include <algorithm>
#include <cmath>

namespace
{
QString singleLineMetadata(QString text)
{
    text.replace(QLatin1Char('\r'), QLatin1Char(' '));
    text.replace(QLatin1Char('\n'), QLatin1Char(' '));
    return text.trimmed();
}

QString formatDataValue(double value)
{
    return QLocale::c().toString(value, 'f', 6);
}

QString fileErrorMessage(const QSaveFile& file, const QString& fallback)
{
    const QString detail = file.errorString().trimmed();
    return detail.isEmpty() ? fallback : QStringLiteral("%1: %2").arg(fallback, detail);
}
}

KFilterCorrectionCurveExportResult exportKFilterCorrectionCurveAsFrd(
    const QString& filePath,
    const KFilterMeasurementCurve& curve,
    const QString& driverDescription,
    const QString& patchLevel)
{
    KFilterCorrectionCurveExportResult result;

    if (filePath.trimmed().isEmpty()) {
        result.errorMessage = QStringLiteral("No output file was selected.");
        return result;
    }

    if (curve.type != KFilterMeasurementCurveType::SplMagnitude) {
        result.errorMessage = QStringLiteral("The selected curve is not an SPL magnitude correction curve.");
        return result;
    }

    if (curve.points().isEmpty()) {
        result.errorMessage = QStringLiteral("The selected driver does not contain a correction curve.");
        return result;
    }

    QVector<KFilterMeasurementPoint> sortedPoints = curve.points();
    std::sort(sortedPoints.begin(), sortedPoints.end(),
              [](const KFilterMeasurementPoint& lhs, const KFilterMeasurementPoint& rhs) {
                  return lhs.frequencyHz < rhs.frequencyHz;
              });

    double previousFrequencyHz = 0.0;
    bool havePreviousFrequency = false;
    for (const KFilterMeasurementPoint& point : sortedPoints) {
        if (!std::isfinite(point.frequencyHz) || point.frequencyHz <= 0.0 ||
            !std::isfinite(point.value)) {
            result.errorMessage = QStringLiteral("The correction curve contains a non-finite or invalid data point.");
            return result;
        }

        if (havePreviousFrequency && point.frequencyHz == previousFrequencyHz) {
            result.errorMessage = QStringLiteral("The correction curve contains duplicate frequencies.");
            return result;
        }

        previousFrequencyHz = point.frequencyHz;
        havePreviousFrequency = true;
    }

    QSaveFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        result.errorMessage = fileErrorMessage(file, QStringLiteral("The FRD file could not be opened for writing"));
        return result;
    }

    bool writeFailed = false;
    {
        QTextStream stream(&file);
        stream.setEncoding(QStringConverter::Utf8);
        stream.setLocale(QLocale::c());

        stream << "* KFilter correction curve\n";
        stream << "* KFilter-Data-Type: magnitude-correction\n";
        stream << "* KFilter-Phase-Meaning: none\n";
        stream << "* Levels are relative corrections, not absolute SPL\n";
        stream << "* Phase is intentionally zero\n";

        const QString safeDriverDescription = singleLineMetadata(driverDescription);
        if (!safeDriverDescription.isEmpty()) {
            stream << "* Driver: " << safeDriverDescription << '\n';
        }

        const QString safePatchLevel = singleLineMetadata(patchLevel);
        if (!safePatchLevel.isEmpty()) {
            stream << "* Patch level: " << safePatchLevel << '\n';
        }

        stream << "* Correction range: "
               << formatDataValue(sortedPoints.constFirst().frequencyHz)
               << " Hz - "
               << formatDataValue(sortedPoints.constLast().frequencyHz)
               << " Hz\n";
        stream << "* Generated by KFilter6\n";
        stream << "* Frequency [Hz]    Correction [dB]    Phase [deg]\n";

        for (const KFilterMeasurementPoint& point : sortedPoints) {
            stream << formatDataValue(point.frequencyHz)
                   << "    " << formatDataValue(point.value)
                   << "    0.000\n";
        }

        stream.flush();
        writeFailed = stream.status() != QTextStream::Ok;
    }

    if (writeFailed) {
        file.cancelWriting();
        result.errorMessage = QStringLiteral("The correction curve could not be written completely.");
        return result;
    }

    if (!file.commit()) {
        result.errorMessage = fileErrorMessage(file, QStringLiteral("The FRD file could not be finalized"));
        return result;
    }

    result.exportedPointCount = sortedPoints.size();
    return result;
}
